# Generated by Django 5.1.1 on 2024-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_item_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Large', max_length=6)),
                ('printer_status', models.CharField(choices=[('Faulty', 'Faulty'), ('Working', 'Working')], default='Working', max_length=8)),
                ('serial_number', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Al Bidda Tower', 'Al Bidda Tower'), ('Al Sadd Club', 'Al Sadd Club'), ('Al Duhai Club', 'Al Duhai Club')], default='Al Bidda Tower', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
